# Generated by Django 2.2.4 on 2019-08-06 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20190806_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author_picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
