# Generated by Django 2.2.4 on 2019-08-06 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_remove_post_author_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='user_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
