# Generated by Django 2.2.4 on 2019-08-08 10:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20190806_0130'),
        ('posts', '0008_auto_20190807_0141'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='author',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='job_name',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Job'),
        ),
        migrations.AddField(
            model_name='author',
            name='phone',
            field=models.CharField(default=27640506930, max_length=15),
        ),
        migrations.AddField(
            model_name='author',
            name='skills',
            field=models.ManyToManyField(to='user.Skill'),
        ),
        migrations.AlterField(
            model_name='post',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 8, 12, 35, 46, 552546)),
        ),
    ]
