# Generated by Django 2.2.4 on 2019-08-08 11:34

import datetime
from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_auto_20190808_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='content',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 8, 13, 34, 50, 612484)),
        ),
    ]
