# Generated by Django 2.2.4 on 2019-08-05 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20190805_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
