# Generated by Django 2.2.4 on 2019-08-05 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20190806_0111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievements',
            name='achievement_icon',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='categories',
            name='category_icon',
            field=models.CharField(max_length=50),
        ),
    ]
