# Generated by Django 2.2.4 on 2019-08-08 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20190806_0130'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
